spring:
  application:
    name: courier-geolocation-tracker
  datasource:
    url: jdbc:h2:mem:courier_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true
    open-in-view: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  cache:
    type: caffeine
  activemq:
    broker-url: vm://embedded-broker?broker.persistent=false
    packages:
      trust-all: true
    embedded:
      enabled: true

courier-app:
  max-number-of-courier-entities: 7 # Number of couriers that producer will use
  producer:
    rate-ms: 50 # Geolocation produce rate in MS
  data-flush:
    rate-ms: 60000 # Data flush from caffeine cache to h2 database in MS
  cache:
    expire-duration-minutes: 60 # Expiration duration in minutes for cache entries

logging:
  level:
    root: INFO
    com.example.couriergeolocationtracker: INFO