spring:
  application:
    name: courier-geolocation-tracker
  datasource:
    url: jdbc:h2:mem:courier_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  cache:
    type: caffeine
  activemq:
    packages:
      trust-all: true
    embedded:
      enabled: true

courier-app:
  producer:
    rate-ms: 500 # Geolocation produce rate in MS
    max-courier-id: 5 # Number of couriers that producer will use
  data-flush:
    rate-ms: 5000 # Data flush from caffeine cache to h2 database in MS
  cache:
    maximum-size: 1000 # Maximum number of cache entries
    expire-duration-minutes: 60 # Expiration duration in minutes for cache entries

logging:
  level:
    root: INFO
    com.example.couriergeolocationtracker: INFO